### ISSUE TITLE
Installation issue with the SPSolution

### ISSUE THREAD

**Issue by dvanboven** [Yvand/AzureCP#86]
When I try to install the AzureCP, I get the following error:

```
Add-SPSolution -LiteralPath "C:\Options\AzureAD\AzureCP.wsp"

Name                           SolutionId                           Deployed
----                           ----------                           --------
azurecp.wsp                    1db45b9b-2fff-4f07-992b-344dde907316 False

PS C:\Users\test> Install-SPSolution -Identity "AzureCP.wsp" -GACDeployment
PS C:\Users\test> $trust = Get-SPTrustedIdentityTokenIssuer "AzureAD"
PS C:\Users\test> $trust.ClaimProviderName = "AzureCP"
Exception setting "ClaimProviderName": "Claim provider with name AzureCP does not exist."
At line:1 char:1
+ $trust.ClaimProviderName = "AzureCP"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

I've checked the following:
```
Get-SPSolution -Identity azurecp.wsp | fl

Name,Deployed,DeploymentState,JobExists

Name            : azurecp.wsp
Deployed        : False
DeploymentState : NotDeployed
JobExists       : False

Get-SPClaimProvider | ft DisplayName

DisplayName
-----------
System
Active Directory
All Users
Forms Auth
User Profile Claim Provider

Get-SPSolution "AzureCP.wsp"| fl Name, Deployed

Name     : azurecp.wsp
Deployed : False

Get-SPFeature "AzureCP"| fl Name, Status

Get-SPFeature : Cannot find a Feature object with Path or Id: AzureCP in scope Local farm.
At line:1 char:1
+ Get-SPFeature "AzureCP"| fl Name, Status
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...mdletGetFeature:SPCmdletGetFeature) [Get-SPFeature], SPCmdletPipeBindException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetFeature
```

I've also restarted the server.

Can you please help me with this?
Thanks in advance!

David

**Comment by Yvand** [comment]
Can you start a new powershell process and check if you have the same errors ?

**Comment by dvanboven** [comment]
Yes, I got the same errors. I also uninstalled it and reinstalled it.
But no luck.

**Comment by Yvand** [comment]
Are you running those commands in the server running central administration?
Does this server run SharePoint web applications service?
Is the deployment of AzureCP solution successful in solutions page?

**Comment by dvanboven** [comment]
Yes, this server is running central administration.
No, I don't see the "Sharepoint Web Applications" service at the server. Or do you mean if this Sharepoint server is hosting the Web Applications? Then, I think yes.
No, the AzureCP solution is not at the "manage farm features".

**Comment by Yvand** [comment]
Can you double check in central admin site > services on server, if the server running central administration is running the service "Microsoft SharePoint Web Applications"?
Deployment may not work if it's stopped on this server.
Can you also check in central admin site > farm solutions if AzureCP.wsp is successfully deployed?

**Comment by dvanboven** [comment]
It's not at the services:
![services](https://user-images.githubusercontent.com/40298841/81974679-2f9d8f00-9626-11ea-9b19-c4fd727749f1.PNG)

It's not at the features:
![features](https://user-images.githubusercontent.com/40298841/81974677-2f9d8f00-9626-11ea-89d7-0bfdc9d6bff3.PNG)

I cannot find "farm solutions" at the Central Administration:
![central_admin](https://user-images.githubusercontent.com/40298841/81974674-2f04f880-9626-11ea-9b2c-ac56262b028a.PNG)

**Comment by Yvand** [comment]
You are unlucky enough to get the issue that happens sometimes with SharePoint, which fails to deploy a solution correctly. To fix it, carefully follow **all** the steps documented on [this page](https://yvand.github.io/AzureCP/Fix-setup-issues.html).

**Comment by dvanboven** [comment]
I've successfully disabled and removed the "AzureCP" SPFeature:
```
DisplayName   : AzureCP
Scope         : Farm
Id            : d1817470-ca9f-4b0c-83c5-ea61f9b0660d
RootDirectory : C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\AzureCP

```
But when I try to disable and uninstall the "AzureCP_Administration" SPFeature, I get the following errors:
```
PS C:\Users\user> Get-SPFeature| ?{$_.DisplayName -like 'AzureCP*'}| fl DisplayName, Scope, Id, RootDirectory

DisplayName   : AzureCP_Administration
Scope         : Web
Id            : 66d8f5d0-2a24-4e46-9ded-8db007e80307
RootDirectory : C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\AzureCP_Administration

PS C:\Users\user> Get-SPFeature| ?{$_.DisplayName -like 'AzureCP*'}| Uninstall-SPFeature -Confirm:$false
Uninstall-SPFeature : The feature with ID '15/66d8f5d0-2a24-4e46-9ded-8db007e80307' is still activated within this farm or stand alone installation. Deactivate this feature in the various locations where it is activated or use -force to force uninstallation of this feature.
At line:1 char:52
+ ... $_.DisplayName -like 'AzureCP*'}| Uninstall-SPFeature -Confirm:$false
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...ninstallFeature:SPCmdletUninstallFeature) [Uninstall-SPFeature], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletUninstallFeature

PS C:\Users\user> Get-SPFeature| ?{$_.DisplayName -like 'AzureCP*'}| Disable-SPFeature -Confirm:$false -Force
Disable-SPFeature : Required parameter URL was not specified for feature '66d8f5d0-2a24-4e46-9ded-8db007e80307'.  The feature was not deactivated.
At line:1 char:52
+ ... splayName -like 'AzureCP*'}| Disable-SPFeature -Confirm:$false -Force
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...tDisableFeature:SPCmdletDisableFeature) [Disable-SPFeature], ArgumentException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletDisableFeature
```

Can you please assist me with this?

p.s. the following commands have not been run:
```
stsadm -o deleteconfigurationobject -id 0E9F8FB6-B314-4CCC-866D-DEC0BE76C237
Remove-SPSolution "AzureCP.wsp" -Confirm:$false
```

**Comment by Yvand** [comment]
Does file `feature.xml` exist in `C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\AzureCP_Administration`, on the server running central administration, and are you running all the commands in that server?
Can you also copy/paste the content of that `feature.xml` file?

**Comment by dvanboven** [comment]
Yes, the file exists in that location. And I've been running all the commands on that same server (we've only got one).

The content of the _feature.xml_:
```
<?xml version="1.0" encoding="utf-8"?>
<Feature xmlns="http://schemas.microsoft.com/sharepoint/" AutoActivateInCentralAdmin="TRUE" Creator="Yvan Duhamel" Description="Adds links to central admin site to access AzureCP settings page - https://github.com/Yvand/AzureCP" Id="66d8f5d0-2a24-4e46-9ded-8db007e80307" Scope="Web" Title="AzureCP Administration pages">
  <ElementManifests>
    <ElementManifest Location="AzureCP.AdminLinks\Elements.xml" />
  </ElementManifests>
</Feature>
```

**Comment by Yvand** [comment]
I think it will work to just add the -Url to Disable-SPFeature cmdlet:

```
Get-SPFeature| ?{$_.DisplayName -like 'AzureCP*'}| Disable-SPFeature -Confirm:$false -Force -Url <CENTRALADMINURL>
```

**Comment by dvanboven** [comment]
Excellent, that was the trick!

But when I execute `Remove-SPSolution "AzureCP.wsp" -Confirm:$false` it gives me the following error:
```
Remove-SPSolution : The solution "azurecp.wsp" has been deployed in the farm. Please retract the deployment before removing the solution.You can also use the -override parameter to forcibly remove the solution, but you will not be able to retract the solution deployment.
At line:1 char:1
+ Remove-SPSolution "AzureCP.wsp" -Confirm:$false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...tRemoveSolution:SPCmdletRemoveSolution) [Remove-SPSolution], SPException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletRemoveSolution
```

Do I need to choose for the "-override"?

**Comment by dvanboven** [comment]
Shall I install it again?

**Comment by Yvand** [comment]
You can absolutely install it again, but before you do that, delete the solution completely, and re-add it from scratch.

**Comment by dvanboven** [comment]
Alright, I installed it again and now I installed it successful. Coming night the server will be restarted and tomorrow I'll test the setup. Keep you posted.

**Comment by dvanboven** [comment]
The installation and configuration is completed successfully, great news!

But at this moment I cannot select users from Azure, only from the on-prem AD. Do you know what's going wrong or how to troubleshoot this?

**Comment by Yvand** [comment]
The easiest way is to look at SharePoint logs and filter on Product/Area "AzureCP"

**Comment by Yvand** [comment]
@dvanboven any update? Can this issue be closed?

**Comment by dvanboven** [comment]
Hi @Yvand , at this moment I'm discussing this with a colleague of mine. She will investigate this error and I'll keep you posted.

Sorry again for the delay

**Comment by dvanboven** [comment]
A colleague of mine told me that she doesn't see any AzureCP values in the logging. It's configured at verbose logging. 

They are visible in the dev environment, which is working fine

**Comment by Yvand** [comment]
Can you follow the steps in https://yvand.github.io/AzureCP/Fix-setup-issues.html to see what exactly is wrong in your setup?

**Comment by dvanboven** [comment]
Is the output below enough? Or do you need some more information?

Get-SPClaimProvider| ?{$_.DisplayName -like "AzureCP"} | fl *

```
DisplayName                 : AzureCP
Description                 : AzureCP
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636
TypeName                    : azurecp.AzureCP
ClaimProvider               : azurecp.AzureCP
ClaimProviderType           : azurecp.AzureCP
IsValid                     : True
UpgradedPersistedProperties : {}

```


Get-SPFeature| ?{$_.DisplayName -like 'AzureCP*'}| fl *

```
Name                        : FeatureDefinition/15/66d8f5d0-2a24-4e46-9ded-8db007e80307
Id                          : 66d8f5d0-2a24-4e46-9ded-8db007e80307
DisplayName                 : AzureCP_Administration
SolutionId                  : 1db45b9b-2fff-4f07-992b-344dde907316
CompatibilityLevel          : 15
ReceiverAssembly            :
ReceiverClass               :
UIVersion                   :
UpgradeReceiverAssembly     :
UpgradeReceiverClass        :
Properties                  : {}
Version                     : 0.0.0.0
Scope                       : Web
AutoActivateInCentralAdmin  : True
ActivateOnDefault           : True
ActivateOnSiteMaster        : False
RootDirectory               : C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\AzureCP_Administration
Hidden                      : False
ActivationDependencies      : {}
AlwaysForceInstall          : False
RequireResources            : False
DefaultResourceFile         :
TypeName                    : Microsoft.SharePoint.Administration.SPFeatureDefinition
Status                      : Online
Parent                      : SPFarm Name=SP2016_Config
DeploymentLocked            : False
Farm                        : SPFarm Name=SP2016_Config
UpgradedPersistedProperties : {}

Name                        : FeatureDefinition/15/d1817470-ca9f-4b0c-83c5-ea61f9b0660d
Id                          : d1817470-ca9f-4b0c-83c5-ea61f9b0660d
DisplayName                 : AzureCP
SolutionId                  : 1db45b9b-2fff-4f07-992b-344dde907316
CompatibilityLevel          : 15
ReceiverAssembly            : AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636
ReceiverClass               : azurecp.AzureCPEventReceiver
UIVersion                   :
UpgradeReceiverAssembly     : AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636
UpgradeReceiverClass        : azurecp.AzureCPEventReceiver
Properties                  : {}
Version                     : 0.0.0.0
Scope                       : Farm
AutoActivateInCentralAdmin  : False
ActivateOnDefault           : True
ActivateOnSiteMaster        : False
RootDirectory               : C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\AzureCP
Hidden                      : False
ActivationDependencies      : {}
AlwaysForceInstall          : False
RequireResources            : False
DefaultResourceFile         :
TypeName                    : Microsoft.SharePoint.Administration.SPFeatureDefinition
Status                      : Online
Parent                      : SPFarm Name=SP2016_Config
DeploymentLocked            : False
Farm                        : SPFarm Name=SP2016_Config
UpgradedPersistedProperties : {}
```

**Comment by Yvand** [comment]
Then you need to follow the step "Recreate missing feature folders and add feature.xml" in https://yvand.github.io/AzureCP/Fix-setup-issues.html to properly remove the AzureCP features.

**Comment by dvanboven** [comment]
The folders within the feature directory are there, so that's good.
At the 25th of May I already uninstalled everything and afterwards I installed en configured it again.

Is it possible to assist me with a remote session or do you've got another tip/trick?

**Comment by Yvand** [comment]
@dvanboven the error message is not related to a setup issue in SharePoint/AzureCP, Graph API is telling you that it does not find the client ID in the tenant you specified, and usually those messages are accurate.
Did you double check this?

**Comment by dvanboven** [comment]
After I received this error, I deleted the original App Registration and I created a brand new one. Afterwards the error disappeared, but still it's not working properly. When I'll add a user to a site, it will only do a lookup within the on-prem AD.

**Comment by Yvand** [comment]
Does AzureCP create the permissions as expected? You can check the SharePoint logs and filter on Product/Area "AzureCP" to confirm this

**Comment by dvanboven** [comment]
When I filter the "Area" at "AzureCP", it's empty. The logfile contains the last 20 minutes.
Or do I need to check the logfile, after I reinstalled the AzureCP?

**Comment by Yvand** [comment]
Indeed, it's only if AzureCP is installed that it will record messages in area "AzureCP"

**Comment by dvanboven** [comment]
I've uninstalled the AzureCP and installed + configured the latest version, but still no luck.

When I use the people picker for the first time, I see the wait cursor for a few seconds and then only the results are being shown of the on-prem AD. When I use the people picker again, the wait cursor disappear after a blink of the eye, but still only on-prem AD users.

When I check the LOG, I see the following:
```
Configuration 'AzureCPConfig' was successfully deleted from configuration database
[AzureCP] Configuration 'AzureCPConfig' was not found in configuration database, use default configuration instead. Visit AzureCP admin pages in central administration to create it.
[AzureCP] Configuration 'AzureCPConfig' changed to version -1, refreshing local copy
[AzureCP] There is no Azure tenant registered in the configuration 'AzureCPConfig'. Visit AzureCP in central administration to add it, or override method GetConfiguration.
[AzureCP] Activating farm-scoped feature for claims provider "AzureCP"
Updated property ClaimsProviderVersion from "" to " " in configuration "AzureCPConfig".
Configuration 'AzureCPConfig' was updated successfully to version 6962605 in configuration database.
Created configuration 'AzureCPConfig' with Id 0e9f8fb6-b314-4ccc-866d-dec0be76c237
Updated property ClaimsProviderVersion from "" to "17.0.20200618.1133" in configuration "AzureCPConfig".
Configuration 'AzureCPConfig' was updated successfully to version 6962626 in configuration database.
Configuration 'AzureCPConfig' was upgraded in configuration database and some settings were updated or reset to their default configuration
[AzureCP] Configuration 'AzureCPConfig' changed to version 6962626, refreshing local copy
[AzureCP] There is no Azure tenant registered in the configuration 'AzureCPConfig'. Visit AzureCP in central administration to add it, or override method GetConfiguration.
Configuration 'AzureCPConfig' was updated successfully to version 6962636 in configuration database.
Claim types list of configuration 'AzureCPConfig' was successfully reset to default configuration
Configuration 'AzureCPConfig' was updated successfully to version 6962638 in configuration database.
Configuration 'AzureCPConfig' was updated successfully to version 6962640 in configuration database.
Configuration 'AzureCPConfig' was updated successfully to version 6962642 in configuration database.
[AzureCP] Configuration 'AzureCPConfig' changed to version 6962642, refreshing local copy
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
[AzureCP] Unexpected error occurred in Initialize, while refreshing configuration: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified., Callstack:    at azurecp.AzureTenant.SetAzureADContext(String claimsProviderName, Int32 timeout)     at azurecp.AzureCP.Initialize(Uri context, String[] entityTypes)
```

Can you please assist me further with this issue?

**Comment by Yvand** [comment]
AzureCP uses [NuGet package Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/5.2.6), which requires System.Net.Http (>= 4.3.4)

* What is the SharePoint version?
* What is the OS version?
* What is the version of "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll" ?
* What is the version of "C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll" ?

**Comment by dvanboven** [comment]
Sharepoint version: Microsoft Sharepoint Server 2016 (Configuration database version: 16.0.4678.1001)
OS version: Windows Server 2016
Clr.dll version: 4.7.3620.0
System.Net.Http.dll version: 4.7.2661.0

**Comment by Yvand** [comment]
Are you by any chance able to test the sample code provided [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8) to validate if System.Net.Http.dll can actually be used on the SharePoint server?

**Comment by dvanboven** [comment]
To be honest, I'm not familiar with testing an C# code, but I've tried it via Visual Studio 2017. I've created a new project and within the project a new classlibrary. The code below I've executed:
```
using System;
using System.Threading.Tasks;
using System.Net.Http;

// HttpClient is intended to be instantiated once per application, rather than per-use. See Remarks.
static readonly HttpClient client = new HttpClient();

static async Task Main()
{
    // Call asynchronous network methods in a try/catch block to handle exceptions.
    try
    {
        HttpResponseMessage response = await client.GetAsync("http://www.contoso.com/");
        response.EnsureSuccessStatusCode();
        string responseBody = await response.Content.ReadAsStringAsync();
        // Above three lines can be replaced with new helper method below
        // string responseBody = await client.GetStringAsync(uri);

        Console.WriteLine(responseBody);
    }
    catch (HttpRequestException e)
    {
        Console.WriteLine("\nException Caught!");
        Console.WriteLine("Message :{0} ", e.Message);
    }
}
```

See screenshot for output/logging:
![classlib_1](https://user-images.githubusercontent.com/40298841/89222272-111bb400-d5d5-11ea-93f3-903930d17807.png)

**Comment by Yvand** [comment]
@dvanboven let's try something more simple, can you run this PowerShell cmdlet and let me know if it succeeds:

```powershell
[System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
```

**Comment by dvanboven** [comment]
Below the output of the version you asked:
```
PS C:\Users\> [System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToke
n=b03f5f7f11d50a3a")
Exception calling "Load" with "1" argument(s): "Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Cult
ure=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
At line:1 char:1
+ [System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
```

Below the output of another (older) version:
```
PS C:\Users\> [System.Reflection.Assembly]::Load("System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll
```

**Comment by Yvand** [comment]
.NET framework is quite up to date and I'm not sure it'll update the assembly.
Let's try to update [System.Net.Http](https://www.nuget.org/packages/System.Net.Http), but it's not that straightforward:

1. In the Visual Studio project you created, add [NuGet package](https://www.nuget.org/packages/System.Net.Http) as a reference. It will download System.Net.Http.dll locally
2. Add System.Net.Http.dll that you just downloaded to the GAC of **all** SharePoint servers:

```powershell
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
$publish = New-Object System.EnterpriseServices.Internal.Publish
$publish.GacInstall("C:\VSProject\System.Net.Http.dll")
Write-Host "Assembly was successfully added to the GAC."
```

**Comment by dvanboven** [comment]
Thanks for your prompt response!
Is this change affecting the whole Sharepoint server/enviroment, or will I only update the .dll for the AzureCP?

**Comment by Yvand** [comment]
The one to use is the one you highlighted. Yes, it will add the assembly to the GAC, so it will be available to everything machine wide (not just AzureCP)
And yes it is compatible with .NET Framework 4.7.2

**Comment by dvanboven** [comment]
Alright, I need to discuss the replacement with a colleague of mine. But he's on holiday, so I'll update you next month.

To summarize it for me:
- I need to copy the highlighted dll to C:\VSProject\
- And run the code below:
```
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
$publish = New-Object System.EnterpriseServices.Internal.Publish
$publish.GacInstall("C:\VSProject\System.Net.Http.dll")
Write-Host "Assembly was successfully added to the GAC."
```

**Comment by Yvand** [comment]
Correct

**Comment by dvanboven** [comment]
> 
> 
> Alright, I need to discuss the replacement with a colleague of mine. But he's on holiday, so I'll update you next month.
> 
> To summarize it for me:
> 
>     * I need to copy the highlighted dll to C:\VSProject\
> 
>     * And run the code below:
> 
> 
> ```
> [System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
> $publish = New-Object System.EnterpriseServices.Internal.Publish
> $publish.GacInstall("C:\VSProject\System.Net.Http.dll")
> Write-Host "Assembly was successfully added to the GAC."
> ```

I've executed this above successfully on a development server and also restarted the server. After the restart I've executed the following:

```
PS C:\Users\spfarm> [System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll
```

It seems not being updated, am I right?

**Comment by dvanboven** [comment]
@Yvand can you re-open this issue or do I need to create a new issue? (sorry for my delay)

**Comment by Yvand** [comment]
@dvanboven I believe this references issue has been completely resolved with [AzureCP 18.0.20201120.1245](https://github.com/Yvand/AzureCP/releases/tag/18.0.20201120.1245), by updating the target framework to .NET 4.7.2.
This version fixes the issue described in https://docs.microsoft.com/en-us/dotnet/standard/net-standard: "For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher."

Can you please test this version and let me know if if fixes the issue?

**Comment by dvanboven** [comment]
Last Saterday I've installed .NET Framework 4.7.2 (NDP472-KB4054530-x86-x64-AllOS-ENU.exe) and also AzureCP has been updated to version 18.0.20201120.1245.

But still I cannot select users from the people picker, which is via AzureCP. Only the on-prem AD will show users.

Also removed the AzureCP and reinstalled it, but still no luck.

**Comment by Yvand** [comment]
Can you confirm what error you see in the logs with this version?

**Comment by dvanboven** [comment]
The logfile won't show anything, regarding this issue. I've put it on "verbose" mode.

**Comment by Yvand** [comment]
Do you see any message from AzureCP?

**Comment by dvanboven** [comment]
When I searched the logfile, I found the records below:
```
Message
Cannot find the type assembly  AzureCP: System.IO.FileNotFoundException: Could not load file or assembly 'AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636' or one of its dependencies. The system cannot find the file specified.  File name: 'AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636'     at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)     at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, ...
The type azurecp.ClaimsProviderLogging, AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636 could not be found in its specified assembly.  Scanning all assemblies that have been loaded in the current app domain.
The type azurecp.ClaimsProviderLogging, AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636 (Id = 3dd2c709-c860-4a20-8af2-0fddaa9c406b) could not be located in any loaded assembly.
```

Could this be the issue?

**Comment by Yvand** [comment]
Yes it's definitely the issue, but I was very confident I fully resolved it by switching to  .NET 4.7.2 (starting with AzureCP 18).
It's very disappointing to see it's still there, and I don't know how to truly identify the dependency your server is missing...

**Comment by dvanboven** [comment]
Last days a colleague of mine did a great job, this with some extensive maintenance of the Sharepoint server:
- issues with the newtonsoft.json dll has been fixed
- several other issues with registering some files has been fixed
- upgrade of Sharepoint has been executed
- lots and lots of other fixes has been executed

During the upgrade the following error appeared:
```
UpgradeBlocking : False
Message         : The [SharePoint - 80] web application is configured with claims authentication mode however the content database you are trying to attach is intended to be used against a windows classic authentication mode.
Remedy          : There is an inconsistency between the authentication mode of target web application and the source web application. Ensure that the authentication mode setting in upgraded web application is the same as what you had in
                   previous SharePoint 2010 web application. Refer to the link "http://go.microsoft.com/fwlink/?LinkId=236865" for more information.
```

The logfile is now clean, regarding the AzureCP :). But still it's not working. Can you please assist me with this issue?
Thanks a lot.

**Comment by Yvand** [comment]
@dvanboven very nice, I would be curious to know exactly how it was resolved.
Based on your screenshot, it seens there is no AAD tenant registered in AzureCP. Did you add it in the AzureCP global configuration page?

**Comment by dvanboven** [comment]
@Yvand I cannot reproduce exactly what my colleague did, but I can ask him if he could update this case.

Yes, the AAD tenant has been registered:
![azurecp_aad-tenant](https://user-images.githubusercontent.com/40298841/104453801-3f9ab380-55a5-11eb-84ed-9e5737fca132.png)

**Comment by wvanderwerf** [comment]
> @dvanboven very nice, I would be curious to know exactly how it was resolved.
> Based on your screenshot, it seens there is no AAD tenant registered in AzureCP. Did you add it in the AzureCP global configuration page?

@Yvand nice to meet! First of all, thanks for your great work regarding this product! I'm the one who can answer your question, and offcourse i'm willing to share as much detail i can. If you have morge questions than answered here below, just ask. For now, i will limit myself to only the relevant parts (as far as there would be stuff left out).

@dvanboven put me on track wat was happening, the issues that came around, en my luck was my programming and Sharepoint background. Not of the level of expert, but enough to be able tot troubleshoot dll issues, GAC, x64 or x32 relevants, view log files and so on.

So to the point! First of all was during registering the dependecies. When running it, there was an error regarding a failure during running the script as mentioned on your website:

$assemblies = Get-ChildItem -Path "C:\Options\AzureAD\AzureCP\*.dll"
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
$publish = New-Object System.EnterpriseServices.Internal.Publish
foreach ($assembly in $assemblies)
{
    $filePath = $assembly.FullName
    $assemblyFullName = [System.Reflection.AssemblyName]::GetAssemblyName($filePath).FullName

    try
    {
        $assemblyInGAC = [System.Reflection.Assembly]::Load($assemblyFullName)
        Write-Host "Assembly $assemblyFullName is already present in the GAC"

        if ($assemblyInGAC.FullName -match "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636")
        {
            # AzureCP must always be overwritten because each version has the same full name
            $publish.GacRemove($assemblyInGAC)
            $publish.GacInstall($filePath)
            Write-Host "Assembly $assemblyFullName sucessfully re-added to the GAC" -ForegroundColor Green
        }
    }
    catch [System.IO.FileNotFoundException] 
    {
        # Assembly.Load throws a FileNotFoundException if assembly is not found in the GAC: https://docs.microsoft.com/en-us/dotnet/api/system.io.filenotfoundexception?view=netframework-4.8
        Write-Host "Adding assembly $assemblyFullName to the GAC"
        $publish.GacInstall($filePath)
        Write-Host "Assembly $assemblyFullName sucessfully added to the GAC" -ForegroundColor Green
    }
}

As this could be referencing to one of the other dll's not registering, or not being installed at all, we started diving in here. Because i wasn't quite sure if:
$assemblyInGAC = [System.Reflection.Assembly]::Load($assemblyFullName)
would throw a catch, we did the resgistration through a loop. Trying to register all files by hand.
It seems to work, but deregistering first and doing a re-register, was failing on Newtonsoft.Json.dll. I could imagine that parsing results with such an old version, could be causing troubles.

So when diving in to this, it seemed that even a gacutil /u /f newtonsoft.json (warning, i do this from the info out of my head. so /uf or /f) which means a forced unregister, wasn't working. The MSI installer package is locking this file.
From my persitence to refresh this registration once again, i removed the lock from the registry by removing the key:
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Assemblies\Global]
de-register works. re-register works also.

After this worked, i saw other errors. One of them pointed me at the WCF data components. I could imagine that the newtonsoft.json dll was referenced here also. So first i tried a reconfigure, but it required a fresh install. This fixes more errors in the event viewer.

But what seems later, after doing some testing. And the need for reinstalling the AzureCP module (i will come back with the reason below), it seems that after removing / uninstalling the CP module, the newtonsoft.json is also uninstalled.
So when this happens, or after a reboot, you get weird errors. Not strange at all, but if you're not awaire, you must do some investigation.

After knowing this, i fixed the dll again. Not yet restored the registry lock yet, but first did some "sharepoint configuration wizard". This one showed other errors. First time run, it run weird (only the option to disconnect from the farm) and a lot errors (before restoring the newtonsoft dll). 
later on (now the .dll was restored) some error that make more sense. They can be split in two area's. 

part1: MSI installer locations nog available:
did a fresh download, made the locations available again, and a lot of reconfiguring happend. (probably some requirements of updates).

part2: content databases which wheren't upgraded yet:
It seems that the movement, migration, upgrade? was done. But after some patching, or after the upgrade to the SP2016 enviroment, there were some databases pending upgrade.

There where some features missing, old references, which aren't used anymore.

So i used: FeatureAdmin from: https://github.com/achimismaili/featureadmin
great tool! After doing some fixing, checks, and cleanup, i was able te do a succesfull sharepoint configuration wizard.
Afterwards, i could the db upgrade by the specified commands in the eventviewer and some information i worked out (sorry, didn't stored the references) but it was the inplace upgrade of the content DB.

After finishing all this, i rebooted the server, and everything was fine. "Clean" event log or at least for what was possible.

From this point, we created a new back-up and started working on the AzureCP tool again. See the information David provided.
Because we can't reproduce the error we started this case with, we do a removal and fresh re-install every time. It seems that the test of adding a user, which should trigger a claim request, is cached. So to make sure we trigger a new request, we re-install the application. Sometime, remove, reboot, and re-install. After the remove, reboot, we had a lot of errors. newtonsoft.json again (grrrr). So restoring the file from the folder you provided on the site, i restored the GAC registry key regarding this file. So it won't be removed again.

I specified as much i can remember, we experencied, so you get a clear view.
In the meanwhile, the server and Sharepoint is patched as far as Windows Update delivers.
So basically, it was a combination of lefover from some patches, hanging dll (re?)registration, and an not upgraded content database. Also missing MSI files which where required to do some re-register / re-install.

For now, we still love to get this one working. I think it's usefuller for future references to open up a new ticket.
But, do you still want to continue with us? Hoping to find a solution to the claim request issues?
The good news here, i will be helping @dvanboven to faster respond to some checks.
Would you like me to open a new ticket? Then we leave this history behind.

Kind regards, Wim

**Comment by Yvand** [comment]
Thank you for all those details on this setup issue, I admit I was hoping that the solution was simpler than that :)
I admit I don't really understand what exactly was wrong with the Newtonsoft DLL but it's really great that you managed to fix it.
Regarding other issues, feel free to open a new issue to treat them separately.

**Comment by brpoddar** [comment]
I had exact same issue 

Application error when access /_admin/azurecp/AzureCPSettings.aspx, Error=Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.  
 at azurecp.ControlTemplates.AzureCPGlobalSettings.<>c__DisplayClass12_0.<ValidateAzureTenantConnection>b__0()    
 at Microsoft.SharePoint.Utilities.SecurityContext.RunAsProcess(CodeToRunElevated secureCode)    
 at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(WaitCallback secureCode, Object param)    
 at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(CodeToRunElevated secureCode)    
 at System.Web.UI.WebControls.Button.OnClick(EventArgs e)    
 at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)    
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Getting Error Message for Exception System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.  File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'    
 at azurecp.ControlTemplates.AzureCPGlobalSettings.<>c__DisplayClass12_0.<ValidateAzureTenantConnection>b__0()    
 at Microsoft.SharePoint.Utilities.SecurityContext.RunAsProcess(CodeToRunElevated secureCode)    
 at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(WaitCallback secureCode, Object param)    
 at Microsoft.SharePoint.SPSecurity.RunWithElevatedPrivileges(CodeToRunElevated secureCode)    
 at System.Web.UI.WebControls.Button.OnClick(EventArgs e)    
 at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)    
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)    WRN: Assembly binding logging is turned OFF.  To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.  Note: There is some performance penalty associated with assembly bind failure logging.  To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].      
 at System.Web.UI.Page.HandleError(Exception e)    
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)    
 at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)    
 at System.Web.UI.Page.ProcessRequest()    
 at System.Web.UI.Page.ProcessRequest(HttpContext context)    
 at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()    
 at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)    
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Windows Server 2016 , if you simply try to load the assembly , we get same error

[System.Reflection.Assembly]::Load("System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

[System.Reflection.Assembly]::Loadwithpartialname("System.Net.Http")

=====
**Resolution was to simply install .net framework 4.7.2**
https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2

Sharepoint server 2016, AzureCP 19.0.20210211.1285 & windows server 2016 which had .Net framework 4.6.2

Hope it saves time & efforts for others.

**Comment by Yvand** [comment]
@brpoddar thank you for sharing. I documented this requirement [here](https://github.com/Yvand/AzureCP/blob/master/CHANGELOG.md#azurecp-170202006181133-enhancements--bug-fixes---published-in-june-22-2020) but clearly it is not easy to find, so I just added a [Prerequisites section here](https://azurecp.yvand.net/docs/overview/introduction/#prerequisites).
